### ISSUE TITLE
Version 2023.12.0 ESPhome

### ISSUE THREAD

**Issue by poudenes** [khenderick/esphome-legacy-addons#2] opened 2024-01-26 12:28 UTC
HI there,

No issue but a question. Is it possible to have 2023.12.0 also in the list?

Greets,
Peter

**Comment by khenderick** [comment] 2024-01-26 12:34
I was planning to add the latest 2023.12.x once the next 2024.2.0 was released (I assume there's no 2024.1.0 due to the holidays).

Or do you have some regressions within 2023.12.x?

**Comment by poudenes** [comment] 2024-01-26 12:38
The specific question for 2023.12.0 is because versions after so > 2023.12.1 gives problems here with ESP.
I only now have BIN files build on 2023.12.0. But want to change something and that's not possible now.

Or if you can tell me how I can do myself build something on my own Github then I can add that link to install it.
All versions later then 2023.12.0 gives problems include the latest one 2023.12.8

**Comment by khenderick** [comment] 2024-01-26 12:44
Do you use a feature from 2023.12.0 that is not in the latest 2023.11.x? 

If not, please do use the latest 2023.11.x, as I try to stick to one version per cycle to reduce the amount of addons people see when adding this repo, and to reduce the overhead on my end.

If you do need 2023.12.0 for a feature not in lastest 2023.11.x but broken in >= 2023.12.1, please point me to the bug report on the ESPHome repo. I'll add 2023.12.0 here and can remove it once the bug is marked as solved 👍.

**Comment by poudenes** [comment] 2024-01-26 14:06
2023.11.0 also ok for me. I'm happy to have this into my workflow now!

**Comment by khenderick** [comment] 2024-01-26 14:08
Glad it can help you out 👍. I'll close this ticket now. If anything pops up, feel free to open another issue.

**Closed as completed by khenderick** 2024-01-26 14:08 UTC
